### ISSUE TITLE
Erroneous classpath/dependencies directory in krangl dependency

### ISSUE THREAD

**Issue by stefanches7** [holgerbrandl/kravis#18]
Apparently, `de.mpicbg` `krangl` artefact is not avaliable solely through jitpack. 
For me it worked with adding `jcentral()` repo to the project. I'm sending a PR with the proposed README update.

**Comment by stefanches7** [comment]
Note that `krangl` has the same issue, but with its `klaxon:0.30` dependency - as far as I understand, it's not being found neither in maven central, nor on jitpack.

**Comment by holgerbrandl** [comment]
Hmm, works for me. But feel welcome to reopen of the problem reoccurs.
