### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by stefanches7** [holgerbrandl/kravis#20]
It would be great to have such a binding working in IntelliJ on Windows. However, there are some problems.

**Comment by stefanches7** [comment]
1. `RUtils` now calls only `bash` and linux-style R path

**Comment by fiddleatwork** [comment]
Can we just update the path or is it more complicated than that?

I need windows support too and I can't figure out if Kravis works on windows due to the R issues.

**Comment by fiddleatwork** [comment]
I can't get it to work with RServe.  I'm going to give up.

It would be good to update the docs saying that kravis does not work on Windows.

**Comment by holgerbrandl** [comment]
Fixed in v0.5.1
