### ISSUE TITLE
Some missing parameters in ElementText

### ISSUE THREAD

**Issue by tokuhirom** [holgerbrandl/kravis#31]
https://ggplot2.tidyverse.org/reference/element.html
https://github.com/tidyverse/ggplot2/blob/HEAD/R/theme-elements.r

I want to pass hjust, vjust and angle to the ElementText.

**Comment by holgerbrandl** [comment]
Thanks @tokuhirom . Well spotted, this part of the ggplot API is currently not well covered in kravis. Would you be willing to add the needed/missing parameters to ElementText via PR? I could push out a new version right after the merge.
