### ISSUE TITLE
Library depends on 0.7 of krangl, can't retrieve dependency from jitpack

### ISSUE THREAD

**Issue by jwill** [holgerbrandl/kravis#8]
The current build relies on 0.7 of krangl which isn't on jcenter, so the dependency fails and the package never builds on jitpack. Here's one of the recent log files.

https://jitpack.io/com/github/holgerbrandl/kravis/afd77dea54/build.log

Fix is to either downgrade jitpack dep to 0.6 or upload the 0.7 build to jcenter. Currently one has to have krangl 0.7 built from source and in their local maven for things to work correctly.

**Comment by holgerbrandl** [comment]
Fixed
